version: '3.8'
name: arol-cloud_data_generation
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  python-server:
    build:
      dockerfile: Dockerfile
      context: "./../python_server"
    depends_on:
      - mongodb
    environment:
      - HOST=python-server
      - MONGO_URI=mongodb://mongodb:27017/arol
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  react-client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./../react_client
    depends_on:
      - python-server
    ports:
      - "3000:80"